### ISSUE TITLE
[kicker]: first entry in submenu gets "selected" when category is opened from "external mouse hover"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#104]
when browsing from category to category, normal behaviour is that no entry of a category is selected.

**Comment by star-buck** [comment]
screencast: https://www.dropbox.com/s/zaysojq8fcgffph/kicker-selected.mkv?dl=0

**Comment by eikehein** [comment]
I think this is likely a regression from this week's overhaul of keyboard navigation, will fix later.
