### ISSUE TITLE
[folderview popup]: missing shadows

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#18]

**Comment by star-buck** [comment]
still no shadows in kci 20150116 with opengl2.0 compositor used

**Comment by mgraesslin** [comment]
Do you have examples where the shadows are still missing? This might require to look at each case individually.

**Comment by davidedmundson** [comment]
I can't reproduce this on the desktop at all.
I've set my application style set to oxygen; clicking on the same places as in the first screenshots.

I can reproduce getting ugly context menus in firefox, this was down to the gtk oxygen theme not being installed.

**Comment by davidedmundson** [comment]
Update: I triggered the missing shadows on the desktop; there is a real problem.

I got it after setting my theme to oxygen and then logging out and back in again.

**Comment by star-buck** [comment]
here might be some clue:
* when oxygen widget theme is set when desktop starts, the "right-click on desktop" shadows are missing
* when you change widget theme to breeze, apply, then change it back to oxygen, shadows are there

maybe something of session is lost after logout?

**Comment by star-buck** [comment]
seems to affect oxygen widget theme and qtcurve theme, maybe its a general problem?

**Comment by star-buck** [comment]
Martin or David?

**Comment by star-buck** [comment]
still shadows are missing (kci 20150403).
Someone fix this?

**Comment by mgraesslin** [comment]
David: you said you were able to reproduce it, can you look at it?

**Comment by davidedmundson** [comment]
Fixed \o/ in a teamwork effort with Martin G in which I gave him a running commentary throughout the day.

It's in review ATM, will mark as ready for packaging when merged.

**Comment by star-buck** [comment]
seems fixed.
