### ISSUE TITLE
[network manager applet]: reload button: "failed to rescan"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#23]

**Comment by sebasje** [comment]
Rescan is a feature in NetworkManager that they're only implementing very reluctantly. (Dan Williams says that the user should never trigger a rescan, and that NetworkManager (i.e. its developers, i.e. Dan himself) knows best when to rescan.

The rescan button has long been a no-op to make the user think that the rescan is happy. I've argued that this is complete non-sense, but "lost" that argument against its maintainers and usability guys. Result of this is that the NM developers don't care about this feature and seem reluctant to implement what we need. NM's codebase, being C, is alien to me unfortunately.

I will track the upstream bugs Aleix has listed and see if something can be done on our side as soon as  NM itself exposes when it's done scanning.

**Comment by davidedmundson** [comment]
We could just turn the notification off? We can do that in the config

It does seem like a silly thing to throw a warning about.
