### ISSUE TITLE
[copy & paste]: only possible while original window is open

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#37]
reproduce:
1. add new text file with some random text in dolphin
2. select & copy random text
3. close kate
4. open firefox
5. try to "Paste" random text into google searchfield is not possible
6. open text file with kate again
7. select and copy random text
8. firefox: able to paste text while leaving kate open, as soon as you close kate the "Paste" option becomes unavailable again

**Comment by star-buck** [comment]
still seems not working in 20150109.
maybe the qt5.4 package is not there or patched in KCI?

**Comment by mgraesslin** [comment]
as said it will be in Qt 5.4.1, which is not yet released.

**Comment by star-buck** [comment]
Which package?

**Comment by star-buck** [comment]
apachelogger: please see if we can patch this into kci

**Comment by mgraesslin** [comment]
package: libqt5gui5
fixed: Dec, 10th
target ISO: unknown

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4691840/+listing-archive-extra

**Comment by star-buck** [comment]
i installed:
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+files/libqt5gui5_5.4.0%2Bdfsg-4ubuntu1%7Eutopic1%7Eppa11_amd64.deb 

still copy&paste seems not working. how can i see if the patch is applied?

**Comment by mgraesslin** [comment]
sorry for asking the stupid question: did you restart the session after installing?

**Comment by star-buck** [comment]
i thought i had rebooted, but trying again now... btw, are there any related packages needed which could prevent the patch to work? like frameworks or plasma packages required?

**Comment by star-buck** [comment]
after reboot still this: 
https://www.dropbox.com/s/6p7xo365dek9vvj/copy-paste.mkv?dl=0

**Comment by star-buck** [comment]
correct link:
https://www.dropbox.com/s/5yrbd0e45ay9p05/copy-paste.mkv?dl=0

**Comment by mgraesslin** [comment]
could you please test with not Firefox - I just want to be sure it's not a side-effect of something else.

**Comment by star-buck** [comment]
dolphin - rename: copy the filename, paste in textfile works, when closing dolphin pasting no longer works.

**Comment by mgraesslin** [comment]
ok, will have to investigate next week. Not on a Qt 5.4 system at the moment.

**Comment by mgraesslin** [comment]
Just tried the steps from Dolphin on my system with the patch. It works as expected.

I'm now a little bit puzzled why it doesn't work with the patched package.

**Comment by star-buck** [comment]
im also puzzled why it doesnt? maybe it does need some other packages required like a certain version of frameworks?

**Comment by mgraesslin** [comment]
I wouldn't be aware of any frameworks dependency - and in any case it should be in the repository already.

What might be possible is that my change in Qt builds up on another required change I wasn't aware of or that more Qt packages are required to update (I'm not a packaging expert after all).

**Comment by notmart** [comment]
Seems that firefox never sends XCB_XFIXES_SELECTION_EVENT_SELECTION_CLIENT_CLOSE when closes

it just sends a bunch of XCB_XFIXES_SELECTION_EVENT_SET_SELECTION_OWNER
if i change qt xcb in the following way, it *seems* to work, but it looks very wrong (as that emit it deliberately avoided in the previous code)


diff --git a/src/plugins/platforms/xcb/qxcbclipboard.cpp b/src/plugins/platforms/xcb/qxcbclipboard.cpp
index f56a29d..2d678e0 100644
--- a/src/plugins/platforms/xcb/qxcbclipboard.cpp
+++ b/src/plugins/platforms/xcb/qxcbclipboard.cpp
@@ -742,7 +742,7 @@ void QXcbClipboard::handleXFixesSelectionRequest(xcb_xfixes_selection_notify_eve
             m_xClipboard[mode]->reset();
         }
         emitChanged(mode);
-    } else if (event->subtype == XCB_XFIXES_SELECTION_EVENT_SELECTION_CLIENT_CLOSE)
+    } else
         emitChanged(mode);
 }

**Comment by mgraesslin** [comment]
I cannot reproduce with Qt5 applications on ISO. E.g. open systemsettings, enter in search, copy the search field content, close window, paste.

But I can reproduce with Qt4 applications on iso and also on my primary system. This explains why I was not able to reproduce with the dolphin example: I had a Qt 5 app here.

**Comment by star-buck** [comment]
oddly enough, copy&paste seems to work in all scenarios with manjaro ISO (tested in LIVE-mode from usb):
http://sourceforge.net/projects/manjarotest/files/0.9.0/kf5-plasma-dev/manjaro-kde-0.9.0-pre2-x86_64.iso/download
Can someone confirm its working and spot the packages they use for why?

**Comment by mgraesslin** [comment]
code review for latest findings: https://codereview.qt-project.org/105556

**Comment by mgraesslin** [comment]
> Can someone confirm its working and spot the packages they use for why?

they use a Dolphin based on Qt 5, so it's not surprising that it works.

**Comment by star-buck** [comment]
But its apparently also working from firefox to kate with ff closed?
Am 06.02.2015 09:33 schrieb "mgraesslin" <notifications@github.com>:

**Comment by mgraesslin** [comment]
> But its apparently also working from firefox to kate with ff closed?

Isn't netrunner using some pre-load hacks to start Firefox during session startup? This might influence the way it tears down. From the investigation there are two different ways to notify that the clipboard is no longer valid. It might be that Firefox uses different pathes. Anyway the patch I created for Qt handles both now. And I do hope there is no third way ;-)

**Comment by star-buck** [comment]
Netrunner 15 doesnt use any preload. Manjaro also seems to work with all
cases tested, gtk2/3, etc., so i wonder what causes it to work and in
kci/netrunner to fail.
Am 06.02.2015 09:52 schrieb "mgraesslin" <notifications@github.com>:

**Comment by mgraesslin** [comment]
only guessing: maybe different GTK versions (Netrunner has 3.12, Manjaro according to distrowatch 3.14), maybe patches to GTK. Maybe different X11 versions with different behavior. The matrix is huge what could influence it.

**Comment by star-buck** [comment]
@apachelogger : is this packaged?

**Comment by apachelogger** [comment]
yep https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4759133/+listing-archive-extra

**Comment by star-buck** [comment]
@apachelogger : okay, thanks
So it does fix most of the copy&paste, can anyone confirm if the patch is applied correctly and works as expected, as firefox seems to still not want to use clipper?

**Comment by mgraesslin** [comment]
I think Marco mentioned that for him it also doesn't work with Firefox. It's not out of the land of possibilities that Firefox needs yet another change. We found two different behaviors, it's not unlikely that there are even more conditions.

**Comment by notmart** [comment]
so, here works with firefox with the following patch in qtbase:
http://paste.opensuse.org/54171834

i'm not sure is a correct thing to upstream, since may have side effects. but can it be tried to be put in the package?

**Comment by apachelogger** [comment]
that is conflicting with https://codereview.qt-project.org/#/c/105556/ are you sure about this?

**Comment by notmart** [comment]
yes, it would replace that one (that one is still technically more correct but yeah... not pretty ;)

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4766467/+listing-archive-extra

**Comment by star-buck** [comment]
does the latest fix the firefox closed in netrunner?

**Comment by star-buck** [comment]
fixes seem to work.
I eventually noticed this though (needs to be confirmed):
If you UNTICK the entry for systray under Extra Items, clipboard seems to be bypassed, since pasting then works fine again only until you close the window where you copy from.

**Comment by mgraesslin** [comment]
> If you UNTICK the entry for systray under Extra Items, clipboard seems to be bypassed, since pasting then works fine again only until you close the window where you copy from.

yes that's to be expected as that item is providing the functionality to restore clipboard content when a window closes. That's the primary reason why Klipper got created in the first place.

**Comment by star-buck** [comment]
and closed!
