### ISSUE TITLE
[oxygen window deco]: needs porting

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#40]
not sure who does this, but for completeness sake when offering oxygen widget style, plasma theme and icons, it shouldn't be missing from plasma5.2

**Comment by star-buck** [comment]
seems still missing in KCI 20150109, @mgraesslin : can you have a look?

**Comment by mgraesslin** [comment]
> can you have a look?

I can contact Hugo and ask whether he will do the port in time of 5.2 release. If he doesn't have the time then we should discuss who does it.

**Comment by mgraesslin** [comment]
I just got a reply from Hugo: he moved it to 5.3 from his side but would appreciate if someone does an initial port for 5.2 even if not finished.

Please note that I would prefer to not have to work on it. I'm not good at UI things and there are IMHO more important things where my development power can be used in a better way.

**Comment by star-buck** [comment]
is this still sensible for 5.2?

**Comment by davidedmundson** [comment]
I started this.

Looks pretty good...
![image](https://cloud.githubusercontent.com/assets/2776077/5788993/4df00454-9e58-11e4-90d7-ffd6c84e9a11.png)

Except there are 5 pages of damn config options, and that radial gradient.
I need at least another 2 days to get them all working.

**Comment by aleixpol** [comment]
@davidedmundson maybe we can get the basic functionality in and Hugo can add all the config options for 5.3?

**Comment by star-buck** [comment]
@davidedmundson : please point to the git source, so harald can package it for netrunner-fixes ppa.

**Comment by davidedmundson** [comment]
in oxygen branch kdecoration2

**Comment by apachelogger** [comment]
oh god that diff

@davidedmundson please merge v5.2.0 in that branch or some other branch so I don't go mental over compiling this into a thing that applies on the 5.2.0t tar :sob:

**Comment by star-buck** [comment]
for netrunner, we can leave that out and delay for plasma 5.3

**Comment by star-buck** [comment]
can we ship this in kci?

**Comment by star-buck** [comment]
please ship in next kci for testing.

**Comment by apachelogger** [comment]
should already be there

sudo apt install kwin-decoration-oxygen

**Comment by star-buck** [comment]
works!
