### ISSUE TITLE
muon5: categories almost all empty

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#57]
reported also here: https://forum.manjaro.org/index.php?topic=18150.msg178093#msg178093

**Comment by aleixpol** [comment]
Will look into this.
Just to make clear, we're talking about making sure it works well on Manjaro or is it the same for Kubuntu/Netrunner?
Maybe the don't have the appinstall information installed over there?

**Comment by star-buck** [comment]
@aleixpol :
since they are also great plasma5 git-master testers with nearly daily ISO updates, best is to ask or help them at manjaro forums.

**Comment by aleixpol** [comment]
Waiting to be accepted to comment on the forums...

**Comment by aleixpol** [comment]
For reference: https://forum.manjaro.org/index.php?topic=19731.0

At the moment it seems like they just don't have the dependencies set up properly.

**Comment by star-buck** [comment]
@aleixpol : on kci from 2 weeks ago, i got _some_ programs to show up in the software categories, but only 2-3 per category
http://pangea-data.s3.amazonaws.com/kci/images/amd64/20150109-1640/kubuntu-plasma5-201501091640-amd64.iso

**Comment by star-buck** [comment]
still the same in latest kci/vivid 20150220.
On startpage, there is already "0AD" listed as top entry, but the entry is missing under "Games" Category, as it is virtually not populated.

**Comment by star-buck** [comment]
seems fixed now
