### ISSUE TITLE
[breeze widget style]: dropdown menu shadows missing in qt4 apps (dolphin)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#70]

**Comment by davidedmundson** [comment]
Did you have Dolphin autostart / restored from a Session? If so this is the same cause as #18.
I'm applying the same fix to Breeze.

**Comment by star-buck** [comment]
i get the shadows onto folderview/desktop just fine now, just dolphin4 still has no shadows for any of its context menus, neither with breeze nor oxygen. I think this is then related to ticket #109 , so ill close here for now.
