### ISSUE TITLE
[krunner]: Opening URLs throws error message

### ISSUE THREAD

**Issue by sebasje** [blue-systems/plasma-5.3#80]
I'm getting an error when opening a URL from KRunner, the dialog says "could not find the program chromium". I had previously set the default webbrowser (systemsettings | default applications | webbrowser) to chromium, but changed it to chromium-browser (the correct binary).

URLs entered into krunner ("google.com" as input for example), throw an error dialog, once the dialog is dismissed, they're opened as requested.

This may be two bugs: the error dialog, and the not picking up the default app correctly. (I've also checked mimetype settings.)

**Comment by vHanda** [comment]
I cannot seem to reproduce this issue. I get no error dialog.

The changing of the defaut browser in not reflected in KRunner without a restart, but that's a separate issue. I'll try to figure out why that is happening.
