### ISSUE TITLE
Advanced power management settings shows empty dropdown for "At Critical Level"

### ISSUE THREAD

**Issue by sebasje** [blue-systems/plasma-5.3#81]
See https://bugs.kde.org/show_bug.cgi?id=344905 reported by Martin.

**Comment by sebasje** [comment]
Fixed upstream with 00eed59164a92c700 in the powerdevil repository, also in 5.2 branch. Needs packaging and verification now.

**Comment by mgraesslin** [comment]
Fixed in latest iso
