### ISSUE TITLE
Wrong cursor shown on background

### ISSUE THREAD

**Issue by mgraesslin** [blue-systems/plasma-5.3#82]
Steps to reproduce:
1. start iso from March, 13th
2. move mouse cursor

observe: on Plasma background it's a default cursor, on actual elements (e.g. start button) it's the expected cursor.

**Comment by star-buck** [comment]
any idea what might be the cause?

**Comment by mgraesslin** [comment]
no, not yet.

**Comment by mgraesslin** [comment]
further observation:
1. go to systemsettings -> Workspace Theme -> Cursor Theme
2. Select another theme
3. Select default (breeze) again
4. click apply
5. kquitapp5 plasmashell
6. plasmashell

-> working cursors

**Comment by mgraesslin** [comment]
most likely reason: Xcursor information is not put on root window. After the change of last comment there is proper information put to root window.

**Comment by mgraesslin** [comment]
I think I understand the problem now and I think it's only in the live installer related to last week's ISO errata: "various glitchery in the installer (missing wallpaper, wrong cursor,
[10:33] <sitter> oxygen icons...)"

There is only the default cursor theme and that doesn't provide the cursor names we expect (XCursor is a bloody mess).

**Comment by mgraesslin** [comment]
Investigation result:
* difference in packaging of breeze and oxygen cursors: breeze does not install files to /etc/X11/cursors/
* /usr/share/icons/default/index.theme which should point to /etc/alternatives/x-cursor-theme misses the following line:
Inherits = breeze_cursors

If that is added and X is restarted, all is fine. Both sddm, and plasmashell pick the right theme.

**Comment by notmart** [comment]
i can confirm that creating such a file with the inherits line in the image fixes cursors in both sddm and plasmashell

**Comment by apachelogger** [comment]
#justxcursormadness

http://kci.pangea.pub/job/vivid_unstable_breeze/109/

the theme package now should:
- /usr/share/icons/default/index.theme -symlinks> /etc/alternatives/x-cursor-theme
- /etc/alternatives/x-cursor-theme -symlinks> /etc/X11/cursors/$theme.theme
- /etc/X11/cursors/$theme.theme is a copy of the theme's respective theme.theme with Inherits=$theme appended
- the standard alternative priority has been increased to force-transit broken installations to the new symlink

**Comment by mgraesslin** [comment]
sounds good.
