### ISSUE TITLE
 [folderview]: "Del"(Entf)-key does not delete marked icons

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#84]

**Comment by eikehein** [comment]
This is a recent regression from the major refactoring to unify the Desktop and Folder View codebases under the hood and actually breaks all keyboard event handling (e.g. also arrows); will fix.

**Comment by eikehein** [comment]
Fixed in http://commits.kde.org/plasma-desktop/1825040801262b34fce9f0f3503737ca275ca794
