### ISSUE TITLE
[sddm breeze theme]: shows "Battery 0%" even if on AC power and mouse is still 50% full

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#89]

**Comment by star-buck** [comment]
same goes for lockscreen: "battery 0%" on a PC desktop on AC with wireless mouse still loaded.

**Comment by mck182** [comment]
This is a bug in power devil and/or the powermanager dataengine, fix should come tonight.

**Comment by davidedmundson** [comment]
Supposedly fixed. (not by me, others are too fast)
Haven't tested myself, needs a battery with mouse on a desktop; but the change looked good.
