### ISSUE TITLE
menu: some installed apps (example: synaptic) do not launch

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#9]
KDEInit could not launch :
Could not open library '/usr/lib/x86_64-linux-gnu/libkdeinit5_'.
Cannot load library /usr/lib/x86_64-linux-gnu/libkdeinit5_: (/usr/lib/x86_64-linux-gnu/libkdeinit5_.so: cannot open shared object file: No such file or directory)

**Comment by star-buck** [comment]
- muon update manager works
- syanptic still fails to launch

**Comment by star-buck** [comment]
interestingly, kmix is also failing to start from menu

**Comment by eikehein** [comment]
Does this happen only with Kicker or also with Kickoff?

**Comment by star-buck** [comment]
kci20150116: muon update manager amd kmix start fine, installed "synaptic" still fails to start from both kicker and kickoff with:

KDEInit could not launch '':
Could not open library '/usr/lib/x86_64-linux-gnu/libkdeinit5_'.
Cannot load library /usr/lib/x86_64-linux-gnu/libkdeinit5_: (/usr/lib/x86_64-linux-gnu/libkdeinit5_.so: cannot open shared object file: No such file or directory)

**Comment by eikehein** [comment]
Regarding the assignment: This isn't really related to Kicker ... Marco, what's the status of your kde-cli-tools patch?

**Comment by shadeslayer** [comment]
I'll have a look at the synaptic issue, I know why it happens, and have a fix for the synaptic package.

**Comment by shadeslayer** [comment]
Atleast Synaptic should be fixed with [this](https://bazaar.launchpad.net/~synaptic-developers/synaptic/trunk/revision/2167) commit. I'm waiting for mvo to push the fix to utopic/vivid. Will comment once its uploaded.

**Comment by star-buck** [comment]
what is the status on this?

**Comment by shadeslayer** [comment]
Utopic was rejected because of : Rejected by Chris J Arges: Upload includes extra debian patch listing, please remove.

Followed up with mvo, waiting for a reply.

**Comment by notmart** [comment]
right now should be fixed with
commit
repo: kde-cli-tools, branch:Plasma/5.2 sha:879258e8710e8a2e1230d64ce10973b2afe38b4e
in conjunction with the patch in the review:
https://git.reviewboard.kde.org/r/120185/
repository kio

**Comment by apachelogger** [comment]
waiting on feedback from Clemens on which frameworks packages to use for patching.

**Comment by star-buck** [comment]
@apachelogger: where can i find the latest frameworks packages in ppa?
we should still package this against the current latest frameworks packages, an easy example to test is also:
paman (and tools), as this seems to especially target gtk programs

**Comment by apachelogger** [comment]
@star-buck regular CI ppas

kio from today:
https://launchpad.net/~kubuntu-ci/+archive/ubuntu/stable/+sourcepub/4697452/+listing-archive-extra

I understand that the review request isn't landed in frameworks though, so we'd need to patch some version of kio in some PPA for testing purposes

**Comment by star-buck** [comment]
so is the version in KCI patched, and can i simply copy it over to fixes ppa?
Otherwise please patch kio and upload in fixes ppa, thanks.

**Comment by apachelogger** [comment]
KCI is never patched. kf5.7 packaging today, so I should be able to patch us a nice KIO 5.7 soonish

**Comment by star-buck** [comment]
where do you put the kf5.7 packages for kci?

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4768509/+listing-archive-extra
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4768506/+listing-archive-extra

these builds depend on kf5.7

**Comment by star-buck** [comment]
seems to work (at least for synaptic in latest KCI20150213)
