### ISSUE TITLE
[Widget Handling Text]: change to: "Press and hold left mouse button on widgets to move them and reveal their handles"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#92]
"Press and hold widgets to..." might seem a bit confusing, the "left mouse button" makes it clearer?

**Comment by eikehein** [comment]
Hmm well that wouldn't work for touch screens though, and one of the feedback items I'm getting is that people love using it on their touchscreen if their laptop has one.

**Comment by star-buck** [comment]
thats right, any other idea for describing the press and hold clearer with a mouse and touch?

**Comment by eikehein** [comment]
Well, I could write "Press and hold using the mouse or a finger" ... but note that idioms like "drag and drop" don't specify an input device either. "Press and hold" is just new (but increasingly common) vernacular. :)

**Comment by star-buck** [comment]
:)
