### ISSUE TITLE
[About KDE popup]: Mentiones Frameworks version, could mention Plasma version as well?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#94]
Since both are KDE Products and Plasma is now universal among form-factors, dialog could add Plasma Version like this:
![about-kde copy](https://cloud.githubusercontent.com/assets/840070/6885398/0a561608-d61f-11e4-8a2e-7506c52781d7.jpg)

**Comment by aleixpol** [comment]
The reason why this isn't like this is that Plasma is not a dependency. In fact, you can run most applications without having a Plasma instance running and, in fact, most applications aren't even related to Plasma.

Maybe what we want is to have a place to show the Plasma About dialog?

**Comment by star-buck** [comment]
Technically you are right, I guess the way it is displayed people could confuse that number with what "KDE" version they are running, especially in a Plasma environment.
Maybe "This program is using Frameworks Version 5.8.0"?
Does anyone know if LXQt uses the "About KDE" dialog to inform about + support KDE/Frameworks?

**Comment by mgraesslin** [comment]
Actually I would say the technical information is completely wrong there. It's about KDE, explaining what KDE is. Why is there a version information? So my call would be: drop it.

In the about application dialog the frameworks version is also showed. In that dialog in my opinion it makes sense to show the Plasma version for all applications of the workspace.
