### ISSUE TITLE
[kicker menu]: submenu window stays open

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#96]
https://www.dropbox.com/s/7u1qfh5860f3yah/kicker-menu.mkv?dl=0

**Comment by eikehein** [comment]
This doesn't happen on my Fedora/git master system; I'll try and see what's up on the ISO soon.

**Comment by star-buck** [comment]
this only seems to "work" when there are exactly two entries under "recent applications" (1 or >3 doesnt work).

**Comment by star-buck** [comment]
maybe one could assume it also needs the two subcategories below to be 2? so I assume only some constellation makes it able to test, so on kci, install english and get 2 items in recent applications, that could be enough to reliable retrigger it.

**Comment by eikehein** [comment]
Fixed in http://commits.kde.org/plasma-desktop/a5bc4ae4f2b1b4ee20887bee02432b4253765e19

**Comment by star-buck** [comment]
seems fixed
