### ISSUE TITLE
[Wallpaper Settings]: Change Button Label "Download Wallpapers" to "Get New Wallpapers"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#98]
That way its consistent with other Button Labels of GHNS:
![get-new-wallpapers](https://cloud.githubusercontent.com/assets/840070/6885498/c4f00d54-d622-11e4-9188-2da2315d4770.png)

**Comment by star-buck** [comment]
Also from that picture, "Install from file" could be better than "Open", since a new wallpaper is also installed somewhat from a (local) wallpaper file? Just addding this for thought.

**Comment by davidedmundson** [comment]
Done the change from the first comment
Will be in next weeks ISO / Plasma 5.3

**Comment by star-buck** [comment]
please add green label "Solved needs packaging" for anything fixed codewise.
